---
title: "Climate predictions"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { icon: "fa-question-circle", href: "https://water.noaa.gov/about/nwm", align: right }
    theme: cerulean
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(shiny)
library(flexdashboard)
library(dataRetrieval)
library(climateR)
library(USAboundaries)
library(USAboundariesData)
library(lubridate)
library(leaflet)
library(sf)
library(dplyr)
library(dygraphs)
library(raster)

source('utils.R')
```

```{r context="server"}
param_lst <- param_meta$terraclim$call

#Initialize Maps 
output$catchMap     <- renderLeaflet({ basemap() })
# output$catchMap2     <- renderLeaflet({ second_map() })
# output$countyMap <- renderLeaflet({ pop_map(pop) })
# comid <<- reactiveValues(comid = NULL)
point <- reactive({
    point <-  input$catchMap_click
    point <-  input$catchMap2_click
})
param <- reactive({
  var <- input$variable1
})

bb2 <- reactive({
  if(is.null(input$catchMap_click)) {
    NULL
  } else {
    click <- input$catchMap_click %>%
      data.frame() %>%
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click,
                        coords = c("lng", "lat"),
                        crs = 4326)
      buffer <- pt %>%
          st_transform(5070) %>%
          st_buffer(30000)
      bb = buffer %>%
          st_bbox() %>%
          st_as_sfc() %>%
          st_transform(4326) 
  }
})


nwm <- reactiveValues()
```



climateR {data-icon="fa-tint"}
=====================================

Inputs {.sidebar}
-------------------------------------

### Model Filters
```{r}
dateRangeInput("dateTS", label = "Date Range Input",
               start = "1993-01-01",
               end = "2018-12-31",
               min = "1993-01-01",
               max = "2018-12-31",
               format = "yyyy mm dd",
               weekstart = 1)
selectInput("variable1",
            label = "Variable", 
            choices = c('prcp', 'rhmax', 'rhmin', 'shum', 'srad', 'wind_dir', 'tmin', 'tmax', 'wind_vel', 'burn_index', 'fmoist_100', 'fmoist_1000', 'energy_release', 'palmer', 'pet_alfalfa', 'pet_grass', 'vpd'))

verbatimTextOutput("buttonInputText")
# verbatimTextOutput("paramText")
verbatimTextOutput("varDropdownText")
verbatimTextOutput("bbText")

```

```{r context = "server"}
# TESTING INPUTS + ACTION BUTTON REACTIVITY
varText <- eventReactive(input$submitButton, {
    paste0("var: ", class(input$variable1))
  })
output$varDropdownText <- renderText({
   varText()
  })

# TESTING INPUTS + ACTION BUTTON REACTIVITY
buttonText <- eventReactive(input$submitButton, {
    paste0("button: ", input$submitButton)
  })
output$buttonInputText <- renderText({
   buttonText()
  })

# paramText <- eventReactive(input$submitButton, {
#     paste0(param())
#   })
# output$paramText <- renderText({
#    paramText()
#   })
bbText <- eventReactive(input$submitButton, {
    paste0(class(bb2()))
  })
output$bbText <- renderText({
   bbText()
  })

# m2 <- do.call(rbind, m1)
# df <- data.frame(m2)[1:5] %>% 
#   tidyr::pivot_longer(cols = 1:5, names_to = "long", values_to = "lng")
# df2 <- data.frame(m2)[6:10] %>% 
#   tidyr::pivot_longer(cols = 1:5, names_to = "lati", values_to = "lat")
# 
# df3 <- bind_cols(df$lng, df2$lat)
# df3 <- setNames(df3, nm = c("lng", "lat")) 
# df3 <- st_as_sf(df3, coords = c("lng", "lat"), crs = 4326)

```
### **Submit**
```{r}
shiny::actionButton("submitButton", label = "Enter", icon("search"))
```

Row
-----------------------------------------------------------------------

### Map1
```{r}
leafletOutput("catchMap")
```

### map 2
```{r}
leafletOutput("catchMap2")
```

```{r context = "server"}
# Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + info panel
  observeEvent(input$catchMap_click, {
   if(!is.null(input$catchMap_click)) {
    click <- input$catchMap_click %>% 
      data.frame() %>% 
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click, 
                        coords = c("lng", "lat"), 
                        crs = 4326)
    
    print("map1_click")
    
    # bb <- pt %>%
    #     st_transform(5070) %>%
    #     st_buffer(30000) %>% 
    #     st_transform(4326)
    # output$comidBox <- renderValueBox({
    # valueBox(value = paste("COMID: ", comid)) })
    
    # fly to bounds
    # bounds <- st_bbox(bb) %>% 
    #       st_as_sfc() %>%
    #       st_buffer(0.2) %>% 
    #       st_bbox() %>% 
    #       as.vector()

      buffer <- pt %>%
          st_transform(5070) %>%
          st_buffer(30000)
      bb = buffer %>%
          st_bbox() %>%
          st_as_sfc() %>%
          st_transform(4326) %>%
          st_as_sf()
      # Map 2 fly to bounds
      bounds <- st_bbox(bb) %>% 
          st_as_sfc() %>%
          st_buffer(0.15) %>% 
          st_bbox() %>% 
          as.vector()
      
      # box <- bb2()
      # variable <- param()
      # clim <- climateR::getGridMET(AOI = box, variable, startDate = "2010-01-01")
      # variable <- clim$variable[[1]]
      
 
    leafletProxy("catchMap") %>% 
      clearMarkers() %>%
      clearShapes() %>% 
      addMarkers(data = pt) %>% 
       addPolygons(data = bb,
                   fillColor = 'red',
                   col = "black",
                   weight = 2) %>%
    flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
    

# 
#     leafletProxy("catchMap2") %>%
#       clearShapes() %>%
#       clearImages() %>%
#       # addRasterImage(x = clim) %>%
#        addMarkers(data = pt) %>%
#        addPolygons(data = bb,
#                    fillColor = 'red',
#                    col = "black",
#                    weight = 2) %>%
#       flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
   }
  })
# # catchMap and catchMap2 are linked while zooming
#   observe({ # Observer to respond to zoom / pan of map1 and apply to map2
#     coords <- input$catchMap_center
#     zoom <- input$catchMap_zoom
#     print(coords)
#     print(zoom)
#     if (!is.null(coords)) {
#       leafletProxy("catchMap2") %>%
#         setView(lat = coords$lat, lng = coords$lng, zoom = zoom)
#     }
# })
#   # catchMap and catchMap2 are linked while zooming
#   observe({ # Observer to respond to zoom / pan of map1 and apply to map2
#     if(is.null(input$variable1)) {
#       NULL
#     } else if (!is.null(var)){
#     var <- input$variable1
#     box <- bb2()
#     clim <- climateR::getGridMET(AOI = box, var, startDate = "2010-01-01")
#     r <- clim$var[[1]]
#     print(var)
#     print(box)
#     
#     leafletProxy("catchMap2") %>%
#         clearShapes() %>%
#         clearImages() %>%
#         addRasterImage(x = r)
#     }
# })
# 
# 
observeEvent(input$submitButton, {
  if(!is.null(input$catchMap_click)) {
    click <- input$catchMap_click %>%
      data.frame() %>%
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click,
                        coords = c("lng", "lat"),
                        crs = 4326)
    var = param()
      buffer <- pt %>%
          st_transform(5070) %>%
          st_buffer(30000)
      bb = buffer %>%
          st_bbox() %>%
          st_as_sfc() %>%
          st_transform(4326) %>%
          st_as_sf()
      # Map 2 fly to bounds
      bounds <- st_bbox(bb) %>%
          st_as_sfc() %>%
          st_buffer(0.15) %>%
          st_bbox() %>%
          as.vector()

      rast <- climateR::getGridMET(AOI = bb, var, startDate = "2010-01-01")
      print("raster1")
        print(var)
      r <- rast$[var][[1]]
    output$catchMap2 <- renderLeaflet({
        second_map() %>% 
          clearMarkers() %>%
          clearShapes() %>%
          clearImages() %>%
          addRasterImage(x = r)
      })
  }
})
      # flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
#   } else if (input$variable1 == "prcp") {
#     click <<- input$catchMap_click %>% 
#       data.frame() %>% 
#       dplyr::select(lat,lng)
#     print(click)
#     pt <- sf::st_as_sf(click, 
#                         coords = c("lng", "lat"), 
#                         crs = 4326)
#       buffer <- pt %>%
#           st_transform(5070) %>%
#           st_buffer(30000)
#       bb = buffer %>%
#           st_bbox() %>%
#           st_as_sfc() %>%
#           st_transform(4326) %>%
#           st_as_sf()
#       # Map 2 fly to bounds
#       bounds <- st_bbox(bb) %>% 
#           st_as_sfc() %>%
#           st_buffer(0.15) %>% 
#           st_bbox() %>% 
#           as.vector()
#       rast <- climateR::getGridMET(AOI = bb, "prcp", startDate = "2010-01-01")
#       print("raster2")
#       prcp <- rast$prcp[[1]]
#       
#       
# 
#   }
# })
# output$catchMap2 <- renderLeaflet({
#   r <- rasterData()
#   leafletProxy("catchMap2") %>%
#       clearMarkers() %>%
#       clearShapes() %>% 
#       clearImages() %>%
#       addRasterImage(x = r) 
#       # flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
# })
```






