---
title: "Climate predictions"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    navbar:
      - { icon: "fa-question-circle", href: "https://water.noaa.gov/about/nwm", align: right }
    theme: cerulean
    orientation: rows
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(shiny)
library(flexdashboard)
library(dataRetrieval)
library(climateR)
library(USAboundaries)
library(USAboundariesData)
library(lubridate)
library(leaflet)
library(sf)
library(raster)
library(dplyr)
library(dygraphs)
library(DT)

source('utils.R')
```

```{r context="server"}
param_lst <- param_meta$terraclim$call
#Initialize Maps 
output$catchMap     <- renderLeaflet({ basemap() })
output$catchMap2     <- renderLeaflet({ second_map() })
# output$countyMap <- renderLeaflet({ pop_map(pop) })
# comid <<- reactiveValues(comid = NULL)
param <- reactive({
  var <- input$variable1
})

click_pt <- eventReactive(input$catchMap_click, {
  click <- input$catchMap_click %>% 
      data.frame() %>% 
      dplyr::select(lat,lng)
    print(click)
    pt <- sf::st_as_sf(click, 
                        coords = c("lng", "lat"), 
                        crs = 4326)
})

raster_data <- eventReactive(input$submitButton, {
  var <-  param()
  bb <- click_to_AOI(click_pt())
  print("click_to_raster")
  click_to_raster(bb, "burn_index", dateRangeText1(), dateRangeText1())
})
# point <- reactive({
#     point <-  input$catchMap_click
#     point <-  input$catchMap2_click
# })

```



climateR {data-icon="fa-tint"}
=====================================

Inputs {.sidebar}
-------------------------------------

### Model Filters
```{r}
dateRangeInput("dateRangeTS", label = "Date Input",
          start = "1980-01-01",
          end = "1985-02-01",
               # value = (Sys.Date() -1),
               min = "1980-01-01",
          max = "2020-01-01",
               # max = (Sys.Date() -1),
               format = "yyyy mm dd",
               weekstart = 1)
# dateInput("dateTS", label = "Date Input",
#           value = "2000-01-01",
#                # value = (Sys.Date() -1),
#                min = "1980-01-01",
#           max = "2010-01-01",
#                # max = (Sys.Date() -1),
#                format = "yyyy mm dd",
#                weekstart = 1)
selectInput("variable1",
            label = "Variable", 
            choices = c('burn_index', 'prcp', 'rhmax',
                        'rhmin', 'shum', 'tmin', 'tmax'))

verbatimTextOutput("dateInputText1")

verbatimTextOutput("dateRangeInput1")

verbatimTextOutput("dateRangeInput2")

# verbatimTextOutput("dateInputText2")

```

### **Submit**
```{r}
shiny::actionButton("submitButton", label = "Enter", icon("search"))
```

Row
-----------------------------------------------------------------------

### Map1
```{r}
leafletOutput("catchMap")
```

### map 2
```{r}
leafletOutput("catchMap2")
```


```{r context = "server"}
# Clicking on map 1 outputs Value boxes on both pages + catchment polygons + Dat table + info panel
  observeEvent(input$catchMap_click, {
   if(!is.null(input$catchMap_click)) {
      pt <- click_pt()
      bb <- click_to_AOI(pt)

      bounds <- st_bbox(bb) %>%
            st_as_sfc() %>%
            st_buffer(0.15) %>%
            st_bbox() %>%
            as.vector()
      leafletProxy("catchMap") %>%
        clearMarkers() %>%
        clearShapes() %>%
        addMarkers(data = pt) %>%
         addPolygons(data = bb,
                     fillColor = 'red',
                     col = "black",
                     weight = 2) %>%
      flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])

      # pred <- pointRaster()

      leafletProxy("catchMap2") %>%
        clearMarkers() %>%
        clearShapes() %>%
        clearImages() %>%
        # addRasterImage(x = pred) %>%
         addMarkers(data = pt) %>%
         addPolygons(data = bb,
                     fillColor = 'red',
                     col = "black",
                     weight = 2) %>%
        flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])
     }

})

# catchMap and catchMap2 are linked while zooming
  observe({ # Observer to respond to zoom / pan of map1 and apply to map2
    coords <- input$catchMap_center
    zoom <- input$catchMap_zoom
    print(coords)
    print(zoom)
    if (!is.null(coords)) {
      leafletProxy("catchMap2") %>%
        setView(lat = coords$lat, lng = coords$lng, zoom = zoom)
    }
})
observeEvent(input$submitButton, {
  if(is.null(input$catchMap_click)){
    NULL
  } else if(!is.null(input$variable1)) {
      var <- param()
      pt <- click_pt()
      bb <- click_to_AOI(pt)

      # Map 2 fly to bounds
      bounds <- st_bbox(bb) %>%
          st_as_sfc() %>%
          st_buffer(0.15) %>%
          st_bbox() %>%
          as.vector()

      # rast <- climateR::getGridMET(AOI = bb, var, startDate = dateText())
      print("raster1")
      print(var)
      # pred <- pointRaster()
        # r <- rast[[var]][[1]]
      r <- raster_data
      # r <- click_to_raster(bb, var, dateText1(), dateText2())
      # r <- r[[var]][[1]]
      leafletProxy("catchMap2") %>%
          clearMarkers() %>%
          clearShapes() %>%
          clearImages() %>%
          # addRasterImage(x = r) %>%
        flyToBounds(bounds[1], bounds[2], bounds[3], bounds[4])

  }
})

# Testing reactive date inputs
# dateText1 <- eventReactive(input$submitButton, {
#     format.Date(input$dateTS)
#   })
# 
# output$dateInputText1 <- renderText({
#    dateText1()
#   })

dateRangeText1 <- eventReactive(input$submitButton, {
    format.Date(input$dateRangeTS[1])
  })

output$dateRangeInput1 <- renderText({
   dateRangeText1()
  })

dateRangeText2 <- eventReactive(input$submitButton, {
    format.Date(input$dateRangeTS[2])
  })

output$dateRangeInput2 <- renderText({
   dateRangeText2()
  })
```

Row
---------------------------------------
### datatable
```{r}
# DT::DTOutput('tidyDatatable')
```

```{r context = "server"}
tidy_data <- eventReactive(input$submitButton, {
  tidy_stack(raster_data(), as_sf = TRUE)
})
# 
# output$tidyDatatable <- DT::renderDT({
#   df <- tidy_data() %>%
#     st_drop_geometry()
#   DT::datatable(tidy_data())
# })
```

### raster plot
```{r}
plotOutput("rasterPlot")
```


```{r context = "server"}
# pointRaster <- eventReactive(input$submitButton,{
#   # predictRaster(tidy_data())
#   r <- raster_data()
#   var = param()
#   empty_raster <- raster::projectExtent(object = r[[var]][[1]],
#                                         crs = r[[var]]@crs) %>%
#     raster::setValues(empty_raster, value = 0)
# 
#   # Convert points to sp
#   agg <- as(tidy_data(), "Spatial")
# 
#   # rastorize prediction points into empty raster grid --- currently rasterizes "last" layer in stack
#   rasterize(agg, empty_raster, field = var)
# })
layer <- eventReactive(input$submitButton,{
  r <- raster_data()

})

output$rasterPlot <- renderPlot({
  r <- layer()
  names(r) <- "burn_index"
  plot(r[["burn_index"]][[1]])
})
```

### timeseries
```{r}
dygraphOutput("predictionGraph")
```

```{r context = "server"}
ts_data <- eventReactive(input$submitButton, {
  bb <- click_to_AOI(click_pt())
 
  # maca <- aggregate_maca(bb, dateRangeText1(), dateRangeText2(), as_sf = FALSE)
  # maca
  clim <- climateR::getGridMET(AOI = pt, var, dateRangeText1(), dateRangeText2())
  clim
})

output$predictionGraph <- renderDygraph({
  var <- param()
  df2 <- ts_data() 
  ts <- timeseries_data(df2) %>% 
    make_timeseries(var)
})
```













